services:
  quickstart:
    container_name: quickstart
    build: .
    command: ["agnt5-init", "--local"]
    env_file:
      - .env
    ports:
      - 63420:3000
      - 63421:63419
    networks:
      - quickstart
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - .venv/

  # quickstart-client:
  #   container_name: quickstart-client 
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   command: ["sleep", "infinity"]
  #   networks:
  #     - quickstart


networks:
  quickstart:
    driver: bridge